spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: product-service
          uri: ${PRODUCT_SERVICE_URI}
          predicates:
            - Path=/api/products/**, /api/reservations/**
        - id: order-management-service
          uri: ${ORDER_MANAGEMENT_SERVICE_URI}
          predicates:
            - Path=/api/orders/**
      discovery:
        locator:
          enabled: true

cors:
  origin: ${CORS_ORIGIN}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}